; EmotionBubblesPointerTable indexes (see engine/overworld/emotion_bubbles.asm)
	const_def
	const EXCLAMATION_BUBBLE ; 0
	const QUESTION_BUBBLE    ; 1
	const SMILE_BUBBLE       ; 2

; slot symbols
DEF SLOTS7      EQU $0200
DEF SLOTSBAR    EQU $0604
DEF SLOTSCHERRY EQU $0A08
DEF SLOTSFISH   EQU $0E0C
DEF SLOTSBIRD   EQU $1210
DEF SLOTSMOUSE  EQU $1614

; StartSlotMachine dialogs
DEF SLOTS_OUTOFORDER   EQU $fd
DEF SLOTS_OUTTOLUNCH   EQU $fe
DEF SLOTS_SOMEONESKEYS EQU $ff

; in game trades
; TradeMons indexes (see data/events/trades.asm)
	const_def
	const TRADE_FOR_CUPPA;BELLSPROUT
	const TRADE_FOR_BRUISER;MANKEY
	const TRADE_FOR_MARCEL;MR_MIME
	const TRADE_FOR_SPOT;NIDORAN_F
	const TRADE_FOR_DUX;FARFETCHD
	const TRADE_FOR_CRINKLES;TANGELA
	const TRADE_FOR_LUCIA;SEEL
	const TRADE_FOR_MOODY;GLOOM
	const TRADE_FOR_TOAST;PONYTA
	const TRADE_FOR_MARC;LICKITUNG
	const TRADE_FOR_TAJIRI;PINSIR
	const TRADE_FOR_TAITO;SLOWBRO
	const TRADE_FOR_NORRIS;GRIMER
	const TRADE_FOR_BRUCE;HITMONLEE
	const TRADE_FOR_JACKIE;HITMONCHAN
	const TRADE_FOR_16
DEF NUM_NPC_TRADES EQU const_value

; in game trade dialog sets
; InGameTradeTextPointers indexes (see engine/events/in_game_trades.asm)
	const_def
	const TRADE_DIALOGSET_CASUAL
	const TRADE_DIALOGSET_EVOLUTION
	const TRADE_DIALOGSET_HAPPY
	const TRADE_DIALOGSET_DAD
	const TRADE_DIALOGSET_SAILOR
	const TRADE_DIALOGSET_FISHER
DEF NUM_TRADE_DIALOGSETS EQU const_value

; OaksAideScript results
DEF OAKS_AIDE_BAG_FULL        EQU $00
DEF OAKS_AIDE_GOT_ITEM        EQU $01
DEF OAKS_AIDE_NOT_ENOUGH_MONS EQU $80
DEF OAKS_AIDE_REFUSED         EQU $ff
